name: Run OpenAI Agent

on:
  workflow_dispatch:

jobs:
  Open-AI-Agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install openai-agents python-dotenv

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # from GitHub secrets
        run: |
          python OpenAI.py